use std::fs;
use std::io::Write;
use std::net::IpAddr;
use std::path::Path;

use super::super::super::NetworkError;
use super::super::types::{DnsBackend, DnsState, ResolvConfInfo};
use super::super::verify::verify_resolv_conf_servers;
use crate::log::events::dns as log_dns;

pub(in crate::platform::linux::network::dns) fn apply_resolv_conf_file(
    info: &ResolvConfInfo,
    servers: &[IpAddr],
    search: &[String],
) -> Result<DnsState, NetworkError> {
    // 仅允许在 resolv.conf 是普通文件时写入，避免与系统管理器冲突。
    if info.is_symlink {
        log_dns::resolv_conf_skipped_symlink();
        return Err(NetworkError::DnsNotSupported);
    }

    let original = fs::read_to_string(&info.path)?;
    let content = build_resolv_conf_contents(servers, search);
    write_resolv_conf(&info.path, &content)?;
    // 写入后必须验证，防止部分系统立即覆盖导致“误判成功”。
    if let Err(err) = verify_resolv_conf_servers(&info.path, servers) {
        let _ = write_resolv_conf(&info.path, &original);
        return Err(err);
    }

    Ok(DnsState {
        backend: DnsBackend::ResolvConf {
            path: info.path.clone(),
            original,
        },
    })
}

pub(in crate::platform::linux::network::dns) fn cleanup_resolv_conf_file(
    path: &Path,
    original: &str,
) -> Result<(), NetworkError> {
    log_dns::resolv_conf_revert(path);
    write_resolv_conf(path, original)
}

// 生成最小 resolv.conf，仅包含 search 与 nameserver。
pub(in crate::platform::linux::network::dns) fn build_resolv_conf_contents(
    servers: &[IpAddr],
    search: &[String],
) -> String {
    let mut content = String::from("# Generated by r-wg\n");
    if !search.is_empty() {
        content.push_str("search ");
        content.push_str(&search.join(" "));
        content.push('\n');
    }
    for server in servers {
        content.push_str("nameserver ");
        content.push_str(&server.to_string());
        content.push('\n');
    }
    content
}

pub(in crate::platform::linux::network::dns) fn write_resolv_conf(
    path: &Path,
    contents: &str,
) -> Result<(), NetworkError> {
    // 直接截断写入，失败则抛出 io error。
    let mut file = fs::OpenOptions::new()
        .write(true)
        .truncate(true)
        .open(path)?;
    file.write_all(contents.as_bytes())?;
    Ok(())
}
